version: "3"
services:
  app1:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: ipdc-dana-platform-1
    restart: always
    ports:
      - 81:5000
    command: bash -c /usr/src/app/start.sh
    env_file: .env
  app2:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: ipdc-dana-platform-2
    restart: always
    ports:
      - 82:5000
    command: bash -c /usr/src/app/start.sh
    env_file: .env
  app3:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: ipdc-dana-platform-3
    restart: always
    ports:
      - 83:5000
    command: bash -c /usr/src/app/start.sh
    env_file: .env 
  app4:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: ipdc-dana-platform-4
    restart: always
    ports:
      - 84:5000
    command: bash -c /usr/src/app/start.sh
    env_file: .env   
  app5:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: ipdc-dana-platform-5
    restart: always
    ports:
      - 85:5000
    command: bash -c /usr/src/app/start.sh
    env_file: .env              
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5
