swagger: "2.0"
info:
  version: "1.0.0"
  title: Dana Api Documentation
  description: Swagger documentation for the Dana project phase-1
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: asad.zaman@apsissolutions.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
schemes:
  - http
paths:
  /login:
    post:
      tags:
        - Authentication
      summary: User login
      description: API for login to Dana Platform.
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Success
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        '500':
          description: Internal Server Error    
  /scheme:
    post:
      tags:
        - Scheme
      summary: Create Scheme
      description: API for creating scheme by Dana Admin.
      parameters:
        - in: body
          name: body
          description: Scheme Payload
          required: true
          schema:
            $ref: '#/definitions/Scheme'
      produces:
        - application/json
      responses:
        '200':
          description: Scheme created Successfull
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error  
        "500":
          description: Internal Server Error

securityDefinitions:
  x-access-token:
    type: apiKey
    name: x-access-token
    in: header

definitions:
  Login:
    properties:
      email:
        type: string
        description: email of the user
      password:
        type: string
        description: Pasword of the user
  Scheme: 
    properties:
      scheme_name:
        type: string
        description: Scheme name 
      rate_of_interest:
        type: number
        description: Rate of interest (%)    
      loan_tenor_in_days:
        type: integer
        description:  Loan Tenor (days)  
      expiry_date:
        type: string
        description: Expiry (day/month/year) for sanction limi 
      grace_periods_in_days:
        type: integer
        description: Grace period (days) 
      penalty_periods:
        type: integer
        description: Penal period (days) 
      daily_penalty:
        type: number
        description: Daily penalty (%)  
      processing_cost:
        type: number
        description: Processing fee (BDT)  
      transaction_fee:
        type: number
        description: Transaction cost (BDT)  
      collection_fee_sharing_with_agency:
        type: number
        description: Collection fee sharing with agency (%)                                                                           
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
