swagger: "2.0"
info:
  version: "1.0.0"
  title: Dana Api Documentation
  description: Swagger documentation for the Dana project phase-1
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: asad.zaman@apsissolutions.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
schemes:
  - http
paths:
  /login:
    post:
      tags:
        - Authentication
      summary: User login
      description: API for login to Dana Platform.
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Success
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  x-access-token:
    type: apiKey
    name: x-access-token
    in: header

definitions:
  Login:
    properties:
      email:
        type: string
        description: email of the user
      password:
        type: string
        description: Pasword of the user
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
